### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by izzy697** [SASUKE-DUCK/dovi-to-hdr-converter#1]
Hello. Could you please help me with converting a DV file to HDR10? I never used Python before. I have all the prerequisites, followed the simplified instructions, but I get nowhere.

This are my results:
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python DoVi.py -i C:\AMD\1\1.mkv -hdr hdr10 --bitrate 8000k
  File "<stdin>", line 1
    python DoVi.py -i C:\AMD\1\1.mkv -hdr hdr10 --bitrate 8000k
           ^^^^
SyntaxError: invalid syntax
>>>

Thnak you in advnace!

**Comment by SASUKE-DUCK** [comment]
you can send me a message to discord if you like( discord user: wks_uwu ), anyway I just updated the python file, try not to use "k" in the script now it would be something like this "python DoVi.py -i C:\AMD1\1.mkv -hdr hdr10 --bitrate 8000"

**Comment by izzy697** [comment]
Thank you for answering me. I'm new to this stuff. I've done video conversions, but only via user-friendly GUI's.
Also, I never used Discord, but I will download it and contact you there.

Unfortunately, I'm still having problems. I downloaded the updated python file and I have Python 3.12 installed.

Here are the results:
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python DoVi.py -i C:\AMD1\1.mkv -hdr hdr10 --bitrate 8000
  File "<stdin>", line 1
    python DoVi.py -i C:\AMD1\1.mkv -hdr hdr10 --bitrate 8000
                ^^^^
SyntaxError: invalid syntax
>>>
